tasks:
  - init: cd smile-methodology && ./gradlew build publishToMavenLocal && cd ../smile-mission && ./gradlew build && cd ..

vscode:
  extensions:
    - openCAESAR.oml-luxor@0.8.2:o/sGt+9y2dbC0/b8p0Lyjw==